---
- name: redmine-reports server configuration
  sudo: yes
  sudo_user: '{{sources_target_user}}'
  template: src=ui_config.json.j2 dest={{sources_target_dir}}/client/etc/config.json

- name: redmine-reports client dependencies install and app rebuild
  sudo: yes
  sudo_user: '{{sources_target_user}}'
  command: '{{item}} chdir={{sources_target_dir}}/client'
  with_items:
     - npm install
     - npm run bower_install
     - npm run build